kind:           ConfigMap
apiVersion:     v1

metadata:
    name:       fichero-configuracion-nginx

data:
    default.conf: |
                    server {
                        listen       80;
                        listen  [::]:80;
                        server_name  localhost;
                    
                        location / {
                            root   /datos;
                            index  index.html index.htm;
                        }
                        error_page   500 502 503 504  /50x.html;
                        location = /50x.html {
                            root   /datos;
                        }
                    }

# /etc/nginx/conf.d/default.conf