kind:           ConfigMap
apiVersion:     v1

metadata:
    name:       fichero-configuracion-nginx

data:
    default.conf: |
                    server {
                        listen       80;
                        listen  [::]:80;
                        server_name  localhost;
                    
                        location / {
                            root   /datos;
                            index  index.html index.htm;
                        }
                        error_page   500 502 503 504  /50x.html;
                        location = /50x.html {
                            root   /datos;
                        }
                    }
---
kind:           ConfigMap
apiVersion:     v1

metadata:
    name:       datos-bbdd

data:
    usuario:            usuario
    nombre_dase_datos:  basedatos
---
kind:           Secret
apiVersion:     v1

metadata:
    name:       datos-bbdd

data:
    contrasenaJefe:     cGFzc3dvcmQ=
    contrasenaUsuario:  cGFzc3dvcmQ=
# echo -n 'password' | base64
---

# /etc/nginx/conf.d/default.conf